#!/bin/bash

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_Mustache_125X_bugFix.root --output_dir results_Ele_Mustache

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoA_125X_bugFix.root --output_dir results_Ele_DeepSC_AlgoA
 
#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoB_125X_bugFix.root --output_dir results_Ele_DeepSC_AlgoB

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoC_125X_bugFix.root --output_dir results_Ele_DeepSC_AlgoC

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoD_125X_bugFix.root --output_dir results_Ele_DeepSC_AlgoD

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourGammasGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_Mustache_125X_bugFix.root --output_dir results_Pho_Mustache

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourGammasGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoA_125X_bugFix.root --output_dir results_Pho_DeepSC_AlgoA
 
#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourGammasGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoB_125X_bugFix.root --output_dir results_Pho_DeepSC_AlgoB

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourGammasGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoC_125X_bugFix.root --output_dir results_Pho_DeepSC_AlgoC

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourGammasGunPt1-100_pythia8_StdMixing_Flat55To75_14TeV_123X_mcRun3_2021_realistic_v11_UL18_pfRechitThres_egmRegNtuples_DeepSC_AlgoD_125X_bugFix.root --output_dir results_Pho_DeepSC_AlgoD

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_DeepSC_AlgoA_pfRechitThres_UL18_2e3sigma.root --output_dir results_scEle_DeepSC_AlgoA_thresUL18

#python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_DeepSC_AlgoA_pfRechitThres_34sigma_235fb.root --output_dir results_scEle_DeepSC_AlgoA_thres235

#python scripts/runEleRegTrainings.py --tag 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_DeepSC_AlgoA_pfRechitThres_UL18_2e3sigma.root --output_dir results_ele_DeepSC_AlgoA_thresUL18

#python scripts/runEleRegTrainings.py --tag 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_DeepSC_AlgoA_pfRechitThres_34sigma_235fb.root  --output_dir results_ele_DeepSC_AlgoA_thres235

python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_Mustache_pfRechitThres_UL18_2e3sigma.root --output_dir results_scEle_Mustache_thresUL18

python scripts/runSCRegTrainings.py --era 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_Mustache_pfRechitThres_34sigma_235fb.root --output_dir results_scEle_Mustache_thres235

python scripts/runEleRegTrainings.py --tag 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_Mustache_pfRechitThres_UL18_2e3sigma.root --output_dir results_ele_Mustache_thresUL18

python scripts/runEleRegTrainings.py --tag 2021Run3 --input_dir /eos/cms/store/group/dpg_ecal/alca_ecalcalib/bmarzocc/Clustering/FourElectronsGunPt1-500_pythia8_PremixRun3_13p6TeV_130X_mcRun3_2022_realistic_v2_235fbNoise_egmRegNtuples_Mustache_pfRechitThres_34sigma_235fb.root  --output_dir results_ele_Mustache_thres235





